### ISSUE TITLE
Update IOOS.us 'Viewers' menu items

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#11]
Change COMT to Coastal and Ocean Modeling Testbed
Change EDS Viewer to EDS Model Viewer

**Comment by kknee** [comment]
and add link to the gliders map called Profiling Gliders

**Comment by kknee** [comment]
@bnfish the profiling gliders map link will need to be updated once we have a production URL, leaving this open for now.

**Comment by bnfish** [comment]
@kknee any update on this?

**Comment by kknee** [comment]
done
