### ISSUE TITLE
COMT Review Updates - Puerto Rico

### ISSUE THREAD

**Issue by rps-jimfrain** [ioos/ioos-us#111]
- [x]	CO-PIs list – include only Johannes Westerink
- [x]	Collaborators List - Juan Gonzalez, Julio Morell, Aurelio Mercado, Reniel Calzada, Volker Roeber, Dongming Yang, Hugh Cobb, Carlos Anselmi, Ernesto Rodriguez, Luis Aponte
- [x]	Federal Partners List – Jamie Rhome (NOAA), Jane Smith (USACE)
- [x]	Model Descriptions – Take out “(UND)” next to ADCIRC

**Comment by kknee** [comment]
all good on dev, thanks!
