### ISSUE TITLE
COMT Review Updates - West Coast

### ISSUE THREAD

**Issue by rps-jimfrain** [ioos/ioos-us#112]
- [x]	Co-PIs list: Christopher Edwards (UCSC), Yi Chao (Remote Sensing Solutions), Parker MacCready (UW), Andrew Moore (UCSC)
- [x]	Collaborators List: Bruce Cornuelle (UCSD), Fei Chai (U Maine)

**Comment by kknee** [comment]
this is all set on dev, thanks!
