### ISSUE TITLE
Navigation to Glider User Group Page from IOOS.us

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#115]
@beckybaltes How do you want to handle navigation to the new glider user group site from ioos.us?  I assume that you want to keep the direct connection to the DAC from the ‘DACS’ menu and link to the user group site from the glider tile?  There’s not really a good menu option for linking to the user group site though?  Should we fit it under ‘Data’?  Create a new menu?

@bnfish @rps-jimfrain

**Comment by BeckyBaltes** [comment]
I think we should keep the DAC connected through the DAC menu drop down, and the glider tile should go to the User Group, which I think will include a link to the DAC?  I don't think the User Group needs to be in the top menu for now, unless that is a bad precedent.  If it should be linked somewhere to the top menu I would suggest we add a new top menu topic.  Maybe "Community" or "User Groups"? I'm not sure if we would host ATN, MBON or HFR user group settings at some future time.

**Comment by kknee** [comment]
_I think we should keep the DAC connected through the DAC menu drop down, and the glider tile should go to the User Group, which I think will include a link to the DAC_

we'll do all of the above and leave off any additional navigation for now.  Can always be added later

**Comment by kknee** [comment]
@rps-jimfrain should be good to go but I can't assign this to you

**Comment by RPSPDuffy** [comment]
This looks to be completed.  The tile on the homepage points to the UG WordPress site.

**Comment by BeckyBaltes** [comment]
This is done, but it looks like I can't close it. Go ahead if you are able to.
