### ISSUE TITLE
Glider DAC Page - About menu not working

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#116]
@bnfish @rps-jimfrain during the DAC page overhaul please make sure to fix the About Menu

the About >> Contact Us item should point back to the ioos.us contact page

I'm not sure about About >> Documents - @beckybaltes, this doesn't go anywhere currently and is inconsistent with the main ioos.us About menu, can we remove?

**Comment by BeckyBaltes** [comment]
Yes, please remove it.

**Comment by Bobfrat** [comment]
I think this is all set and can be closed
