### ISSUE TITLE
HFRADAR Landing Page - Navigation Bug

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#117]
@bnfish just noticed that we have two 'Data' menus and no visualization menu here: https://hfradar.ioos.us/.

Can you make this consistent with the main ioos.us nav bar?

**Comment by kknee** [comment]
same issue with gliders page.

**Comment by gitchrisadams** [comment]
This issue was resolved with: https://github.com/ioos/ioos-us/issues/173 and is deployed: https://hfradar.ioos.us/
