### ISSUE TITLE
Update mailto: in Footer

### ISSUE THREAD

**Issue by mwengren** [ioos/ioos-us#118]
The current mailto address in the footer of IOOS.us needs to be changed to 'webmaster.ioos.us@noaa.gov' from 'ioos.catalog@noaa.gov'.

**Comment by kknee** [comment]
@kellydesent

**Comment by mwengren** [comment]
@kknee @kellydesent I have an update on this issue.  Happened to be looking at ioos.us this morning and noticed the info also needs to be updated on the 'Contact Us' page (https://ioos.us/contact-us).  

Also, I had made some changes via [PR](https://github.com/ioos/ioos-us/commit/42302d0bc343219c115cd14aa09469386e6e5fd2) to the code base awhile ago to change the footer email and other info, although it looks as though they haven't been deployed yet since the site still shows the old info.  That's fine, but let's make sure that we keep the new address and phone number from the PR, and add those also to the Contact Us page.  

I noticed though that I used the wrong email address in the PR, let's just use 'webmaster.ioos.us@noaa.gov' in both places when you resolve and close this issue.  Replace 'data.ioos@noaa.gov' in both locations.

**Comment by mwengren** [comment]
Hmm, well, I stand corrected.  Looks like maybe the Contact Us page has it's own, separate footer (with old info).  So, to close this issue, it might be best to get to the bottom of why Contact Us uses a different footer, see if any other pages do as well, and also please update the email address to 'webmaster.ioos.us@noaa.gov' in all locations.

**Comment by rps-aaron** [comment]
This is completed in #176
