### ISSUE TITLE
UG2 Publications Page

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#140]
Per my conversation with Jim, we want to add a publication list to the UG2 page.  It should be linked in the left menu under the Glider Activities Header as the top menu item "Publications".  The pubs should be listed like journal references and they should be binned by year. I think we should have 2017, 2016, 2015, and "Prior to 2015."  Jim had said he could put tabs at the top for going between the years.  We'll add years as we go, but the front tab should be the most recent.  For an initial set of articles, I'd like to use the references in the [Glider White Paper](https://gliders.ioos.us/files/natl_glider_ntwrk_plan_final.pdf).  They are in Appendix A. If it is too hard to extract from the pdf, I should have a word version of the doc that I can send.

**Comment by kellydesent** [comment]
I added the page and content. Please review when you have a chance and let me know if you would like any changes made to the page.

**Comment by BeckyBaltes** [comment]
The content looks good. I saw that you added the years, but all the pubs aren't listed in the year category. I think they are all from before 2015, so can you also post them there? I think the Publications tab can have everything and then each year can be a subset.  In this case, everything that's been added can go in the pre-2015 tab.  Keeping them alphabetical by author seems good.

**Comment by kellydesent** [comment]
I checked them all to make sure they were prior to 2015 and they were, so I also added them into that category. Let me know if you would like any other changes.

**Comment by BeckyBaltes** [comment]
I think this is good for now. Do you know what the level of effort would be to set up the year tabs across the top, similar to the way the ioos.noaa.gov does it?  An example is https://ioos.noaa.gov/project/comt/ where the tabs are "about," "Projects," and "documents."  Otherwise, there is a UG2 meeting on Friday and I will make sure the leadership team is good with this but we can probably close out the task until something new is identified.

**Comment by kellydesent** [comment]
I set up the page to work like that link with the tabs. Can you take a look and tell me what you think? When one of the links at the top is clicked, the page jumps down to that section of time. Since there is no publications in 2015-2017, it is blank. But you can test it with "Prior to 2015". Also, if you would like to leave it like this, do you still want the sub page categories with the different publication dates, or should I remove those? Please let me know if there are any other changes you would like made.

**Comment by BeckyBaltes** [comment]
Oh, I like that.  Can you just put "To be added" for the years where we don't have any yet? I hope we're able to add some pretty quickly so they shouldn't stay empty for long.

**Comment by kellydesent** [comment]
Sounds good. I added that text in. Would you like to keep the sub categories on the left that separate the publications into each year per page, or should I remove them?

**Comment by BeckyBaltes** [comment]
I think remove the categories on the left side menu.

**Comment by kellydesent** [comment]
This is completed. Let me know if you would like any other changes.

**Comment by BeckyBaltes** [comment]
Looks good. If anything new comes up we can start a new issue.
