### ISSUE TITLE
UG2 Menu Update: Remove color change from hover in top menu items

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#141]
In the UG2 side menu bar, the top items all highlight to yellow when you hover over them(Underwater Glider User Group, Data Management, Glider Activities, About Us), but they don't link to anything. Can you remove the color change so it's not confusing for users?

**Comment by RPSPDuffy** [comment]
This should be all set.  We kept the hover over on Underwater Glider User Group since this is a link back to the home page on the sub pages.

**Comment by BeckyBaltes** [comment]
That works for me.
