### ISSUE TITLE
Wordpress Access for Becky

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#142]
@bnfish Can you provide me access to the wordpress site, so I can start looking around and getting familiar with it? I would like to have you still do major set up changes but I can edit/add content like calendar events, publications, etc...

**Comment by RPSPDuffy** [comment]
@BeckyBaltes I just sent you an email with this information.  Please let us know if you have any questions.

**Comment by BeckyBaltes** [comment]
Got it. Thanks!
