### ISSUE TITLE
Add Abstract Titles for OSM to UG2 Site by 29 Sep

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#143]
In preparation for our next UG2 Leadership Meeting, I'd like to show progress on some of their website suggestions.  One suggestion was to add abstracts for talks at the OSM to our upcoming meeting tab.  On https://ug2.ioos.us/meetingsevents/, under the upcoming AGU Ocean Sciences Meeting, I would like to start a list of abstract authors and titles beginning with the list in our session, https://agu.confex.com/agu/os18/preliminaryview.cgi/Session28052. Is this feasible?

**Comment by RPSPDuffy** [comment]
Just to confirm, you want us to take the Titles and Authors from  https://agu.confex.com/agu/os18/preliminaryview.cgi/Session28052 and add that content to the meetingsevent page?

Do you want it listed by author then title or title and then author?  Also do you want it in the same order from the confex.com website or a different order?

Navigating gliders with GHOST: virtual and in water demonstrations (305063) 
Charlie N. Barron

or

Charlie N. Barron
Navigating gliders with GHOST: virtual and in water demonstrations (305063)

**Comment by BeckyBaltes** [comment]
My preference is alphabetical by author and author first, then title. Yes, I would like to start with the 14 abstracts listed at that link.

**Comment by RPSPDuffy** [comment]
We added the text today.  Please review when you have a chance and let me know if you would like any changes or any additional content add to the page.

**Comment by BeckyBaltes** [comment]
I think this is a good start. When the AGU schedule is published, I think we will want to add what session other talks are in. These are all in one session.  I'm not sure what the best identifying information for the session is, but I will confer with the other UG2 team members on our Friday call. I think for now, we can close this task.
