### ISSUE TITLE
Add Breadcrumbs back to COMT pages

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#149]

**Comment by kknee** [comment]
@kellydesent 

We have breadcrumbs at the dataset set level, e.g. click Project:
https://ioos.us/comt/projects/extratropical_inundation then the
_2005 UMASS FVCOM 3D no wave_ button

But at the project level, e.g. https://ioos.us/comt/projects/extratropical_inundation

There is no way to get back to the homepage, would be good to add breadcrumbs like:

Coastal and Ocean Modeling Testbed > Coastal Waves, Surge and Inundation in the Gulf of Maine

**Comment by rps-aaron** [comment]
@Bobfrat I added the html for the breadcrumbs in branch comt-breadcrumb but something additional has to be done to populate the text.  Can you let me know if this is something I can do and, if so, point me in the right direction.  Otherwise assign accordingly for someone to complete this item.

**Comment by rps-aaron** [comment]
this was resolved by @gitchrisadams with pr #177

**Comment by gitchrisadams** [comment]
This is live: Example: https://ioos.us/comt/projects/cb_hypoxia
