### ISSUE TITLE
Update sub links for glider home page (gliders.ioos.us)

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#155]
@kellydesent, @Bobfrat ,  Since we have updated the glider user group to be the entry point for all things gliders and not just the user group, I would like to update the front page text.   I would like to maintain the current page, but have it at  https://ug2.ioos.us/gliders-forum/.  (Note: I'd like to update this to be gliders.ioos.us/usergroup as noted in Issue #146.)

On the main gliders.ioos.us, I would like to have the title read "Underwater Gliders."

Beneath that as a description, the following text:

"Gliders are a unique and important observing system used to serve a variety of subsurface observing missions.  Gliders can monitor water currents, temperature, tagged animals and conditions that reveal effects from storms, impacts on fisheries, and the quality of our water. This information creates a more complete picture of what is happening in the ocean, as well as trends scientists might be able to detect. These versatile vehicles collect information from deep water, as well as at the surface, at lower cost and less risk than ever before. As scientists deploy more gliders, they are revolutionizing how we observe our ocean. These robots propel us closer to that revolution.

IOOS is now supporting an Underwater Glider User Group (UG2) as well as a glider Data Assembly Center (DAC). Please see more information about both using the links to the left."

I'll need to add a picture at some point, but I don't have one yet.

**Comment by Bobfrat** [comment]
Adding @gitchrisadams to discussion because he is updating the links on the main gliders.ioos.us page.

**Comment by gitchrisadams** [comment]
@BeckyBaltes 
This has now been updated, see screenshot below.

![image](https://user-images.githubusercontent.com/9978238/32894881-2cee5c0a-caac-11e7-9d1d-0b9a8b466ce5.png)

**Comment by BeckyBaltes** [comment]
@gitchrisadams This new text looks great.  Can you delete the text that is under the picture since it's now on the usergroup page instead?

**Comment by gitchrisadams** [comment]
@BeckyBaltes Should be all set, let me know if that looks o.k.

**Comment by BeckyBaltes** [comment]
Looks good. I think we can close.
