### ISSUE TITLE
Fix gliders.ioos.us navigation menu issues

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#157]
In particular

-  the IOOS Glider DAC link should go to https://gliders.ioos.us/data/
- this link for the QC manual doesn't work: https://gliders.ioos.us/Manual-for-QC-of-Glider-Data_05_09_16.pdf

@Bobfrat @gitchrisadams

**Comment by Bobfrat** [comment]
should be set

**Comment by kknee** [comment]
@Bobfrat the link to the QC manual, both on the page and the one listed above doesn't work.

@kellydesent can you look at this and ask @gitchrisadams and @Bobfrat questions as needed?

**Comment by kellydesent** [comment]
It doesn't look like the file was uploaded into WordPress. @Bobfrat and @gitchrisadams do either of you know where I can find the file so I can upload it?

**Comment by gitchrisadams** [comment]
[Manual-for-QC-of-Glider-Data_05_09_16.pdf](https://github.com/ioos/ioos-us/files/1767646/Manual-for-QC-of-Glider-Data_05_09_16.pdf)

Gave this to @kellydesent via Skype, but wanted to include here for reference as well.

**Comment by kellydesent** [comment]
This is completed.

**Comment by Bobfrat** [comment]
@kknee the link to the Glider manual works from the GliderDAC page. It's this link:
https://gliders.ioos.us/data/files/Manual-for-QC-of-Glider-Data_05_09_16.pdf.
