### ISSUE TITLE
Integrated Ocean Observing System header link on gliders.ioos.us wrong

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#161]
Can you look at the top menu Integrated Ocean OBserving System link at the top of the gliders.ioos.us page. It redirects to gliders.ioos.us, but it should redirect to ioos.us.

**Comment by gitchrisadams** [comment]
![image](https://user-images.githubusercontent.com/9978238/33022765-3e6ea572-cdd4-11e7-8f34-2c74e151151f.png)

@Bobfrat @BeckyBaltes This should be all set.

**Comment by BeckyBaltes** [comment]
Looks good.
