### ISSUE TITLE
COMT Map link wrong on gliders.ioos.us

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#162]
@gitchrisadams the Viewers banner has the wrong COMT map link in the drop down on the gliders.ioos.us page.  It should be http://oceansmap.com/comt/.

**Comment by gitchrisadams** [comment]
@BeckyBaltes Should be all set now.

**Comment by BeckyBaltes** [comment]
Yep. looks right. Thanks.
