### ISSUE TITLE
Link updates for gliders.ioos.us

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#163]
@gitchrisadams Kyle's keeping us honest.

On gliders.ioos.us, the viewer drop down has the old gliderdac link. It should be gliders.ioos.us/data.

Also, Can you make the glider map screengrab on gliders.ioos.us clickable and direct to https://gliders.ioos.us/map/?

**Comment by gitchrisadams** [comment]
@BeckyBaltes Viewer drop down or DAC dropdown for old gliderdac link?

**Comment by gitchrisadams** [comment]
@BeckyBaltes Map image is now clickable.

**Comment by gitchrisadams** [comment]
@BeckyBaltes I updated gliderdac in DAC drop down to: gliders.ioos.us/data and the profiling gliders link in the Viewers drop down to http://gliders.ioos.us/map so should be all set.

**Comment by BeckyBaltes** [comment]
Looks good.
