### ISSUE TITLE
Publications Sorting on Glider User Group

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#164]
@kellydesent Can you fix the glider user group publications page so when you click on the years at the top it takes you to that year in the listing?  I added pubs to the other years 2017,2016, and 2015, so the links will be more useful now. It looks like they are linked, but links aren't working.

**Comment by kellydesent** [comment]
@BeckyBaltes This should be all set. Let me know if you would like anything else. Thanks.

**Comment by BeckyBaltes** [comment]
Looks good. We'll probably want to add a 2018 tab soon, but until we have any pubs in 2018, we can probably leave it. Thanks.
