### ISSUE TITLE
Fix formatting on https://gliders.ioos.us/meetingsevents/

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#166]
@kellydesent I made some updates to the meetings page and I can't get the formatting quite right. Can you take a look. I have links for all events at ocean sciences, but the Townhall link doesn't change the text color so you can't tell there is a link.  Also I moved "Past Events" to the bottom of the page, but it justified all the way to the left and I can't get it to line up with everything else.

**Comment by kellydesent** [comment]
@BeckyBaltes The formatting issues should be all set. Please take a look and let me know if you'd like anything else. Thanks. https://gliders.ioos.us/meetingsevents/
-Kelly

**Comment by BeckyBaltes** [comment]
Thanks Kelly, I plan to add a few webinars, so I may have to reach out again, but this looks good.
