### ISSUE TITLE
UG2 Page updates

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#172]
@kellydesent 
- Can you underline the "Workshops/Meetings" header or tell me how? I have an italics and Boldface feature but no underline.
- Can you also add a new category to the Table of Contents under "Meetings/Events" for "Job Postings"? 
Then when add these two as starter jobs? Just list the following and link them to these attachments?
1. Postdoc in Oceanography, BIOS
2. Glider Tech, BIOS
[PostdocadvertisementMar2018.pdf](https://github.com/ioos/ioos-us/files/1838700/PostdocadvertisementMar2018.pdf)
[GliderTech_posting.pdf](https://github.com/ioos/ioos-us/files/1838701/GliderTech_posting.pdf)

**Comment by gitchrisadams** [comment]
I updated Workshops/Meetings to have an underline. Just for reference as to what I did. I had to click on the text tab and enter a <u> and closing </u>. In visual mode there doesn't seem to be a underline option. 
![image](https://user-images.githubusercontent.com/9978238/37791417-83753260-2ddf-11e8-9487-cfdb63a679f0.png)

I'm also currently look int at those other issues posted in this issue as well.

**Comment by BeckyBaltes** [comment]
Thank you.

**Comment by gitchrisadams** [comment]
@BeckyBaltes I updated to include a basic Job postings page with those two job postings as an ordered list, with link added to table of contents. If you want anything there changed or added, let me know.

**Comment by BeckyBaltes** [comment]
Looks good 2 quick edits
2nd job, can you edit to BIOS (not BIO).  Also can you add ",posted 3/22/18" next to each one.

**Comment by gitchrisadams** [comment]
@BeckyBaltes Sorry about the Bio/Bios thing, copy paste erorr, didn't grab all of it. It is updated now with the date.

**Comment by BeckyBaltes** [comment]
Looks great. Thanks for the quick response!
