### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fgayanilo** [ioos/ioos-us#179]
The link to NDBC THREDDS (https://sdf.ndbc.noaa.gov/thredds/), returns a 404.

**Comment by gitchrisadams** [comment]
@fgayanilo Can you tell me what page/url that link was on?

**Comment by fgayanilo** [comment]
https://hfradar.ioos.us/ --> click on Data Visualization & Access  --> Access Data via NDBC THREDDS Server

**Comment by gitchrisadams** [comment]
@fgayanilo Got it, thanks.

**Comment by gitchrisadams** [comment]
@mwengren and @BeckyBaltes This link is broken: https://sdf.ndbc.noaa.gov/thredds/  But on website I noticed this: Please note that the HF Radar WCS/THREDDS has moved to https://dods.ndbc.noaa.gov/thredds/hfradar.html Does that link look right for the Data Visualization & Access --> Access Data via NDBC THREDDS Server link?

**Comment by mwengren** [comment]
They did change their URLs ~ 6 mos ago.  That looks like the right one to me.

**Comment by gitchrisadams** [comment]
Thanks @mwengren  I updated the url and is deployed
![image](https://user-images.githubusercontent.com/9978238/40433246-8eb63744-5e79-11e8-8708-338090d86000.png)

**Comment by fgayanilo** [comment]
well done; link updated.
