### ISSUE TITLE
data.ioos.us redirect problem

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioos-us#18]
Still points to http://data.ioos.us/gliders/erddap/index.html

**Comment by kknee** [comment]
@dpsnowden it points to the CKAN page for me.  Can you double check?  Maybe try clearing your cache first?

**Comment by dpsnowden** [comment]
yeah that worked (he said sheepishly)

**Comment by lukecampbell** [comment]
Yeah it's going to require a hard cache clear. The old redirect was a "permanent redirect" so browsers won't even request updates without a hard cache clear.
