### ISSUE TITLE
Create RA Page

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#19]
Start by taking the image from here:

http://ioos.wpengine.com/ioos-region-map/

We'll want each target to link to the RA data page.  I'll put a list of links here when I have them.

**Comment by kknee** [comment]
Links:

AOOS:
CariCOOS:
CenCOOS
GLOS: http://data.glos.us/portal
GCOOS:
MARACOOS: http://assets.maracoos.org/
NERACOOS:
PacIOOS:
NANOOS:
SECOORA:
SCCOOS:

**Comment by robragsdale** [comment]
AOOS: http://portal.aoos.org/
CariCOOS: http://www.caricoos.org/drupal/
CeNCOOS: http://data.cencoos.org/
GCOOS: http://data.gcoos.org/
NANOOS: http://nvs.nanoos.org/Explorer
NERACOOS: http://neracoos.org/realtime_map
PacIOOS: http://oos.soest.hawaii.edu/pacioos/voyager/
SCCOOS: http://www.sccoos.org/data/overview/
SECOORA: http://secoora.org/maps/

**Comment by kknee** [comment]
thanks @robragsdale!  @bnfish you're good to move forward with this one.
