### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by Bobfrat** [ioos/ioos-us#191]
Need to track metrics so let's add GA to ioos.us

**Comment by gitchrisadams** [comment]
Check/confirm/add Google Analytics to:
- [ ] ioos.us
- [ ] OSMC
- [ ] Ocean Acidification
- [ ] gliders.ioos.us
- [ ] comt.ioos.us
- [ ] https://hfradar.ioos.us/
- [ ] https://atn.ioos.us/
- [ ] https://sensors.ioos.us/
- [ ] registry.ioos.us
- [ ] https://mbon.ioos.us/

**Comment by gitchrisadams** [comment]
All are deployed, so closing.
