### ISSUE TITLE
DACS menu item links need updating

### ISSUE THREAD

**Issue by Bobfrat** [ioos/ioos-us#195]
On gliders.ioos.us and comt.ioos.us (and likely all the others) the hyperlinks on the DACS menu items need updating. GliderDAC url should be https://gliders.ioos.us. ATN DAC should point to https://atn.ioos.us/

**Comment by gitchrisadams** [comment]
gliders.ioos.us top links and left sidebar are now updated/live.

**Comment by gitchrisadams** [comment]
This has been updated and deployed to all sites listed above so closing this issue.
