### ISSUE TITLE
ATN link

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/ioos-us#201]
I tried to go to the ATN DAC link from the [glider ioos.us](https://gliders.ioos.us/data/) page and hit an outdated/forbidden link: https://oceanview.pfeg.noaa.gov/ATN/

Can you pls change the ATN DAC link to https://atn.ioos.us/?  Looks like this is correct on the main ioos.us page and on the HFR DAC page, so just the Glider DAC page needs the updated link.

**Comment by Bobfrat** [comment]
@kbailey-noaa this has been updated
