### ISSUE TITLE
Change EDS Model Viewer name 

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/ioos-us#202]
On the IOOS.US page, change "EDS Model Viewer" to "IOOS Model Viewer" on the thumbnail.

**Comment by kellydesent** [comment]
https://github.com/ioos/ioos-us/pull/203

**Comment by Bobfrat** [comment]
@kbailey-noaa Probably also want it changed on all the ioos.us Viewers drop downs? I see it on https://comt.ioos.us/, https://gliders.ioos.us/ etc etc?

<img width="374" alt="Screen Shot 2020-01-16 at 8 31 58 AM" src="https://user-images.githubusercontent.com/5702672/72529237-d6ba1780-383a-11ea-924a-2db1c28774ae.png">

**Comment by kbailey-noaa** [comment]
@Bobfrat  Yes please!  Good catch.

**Comment by Bobfrat** [comment]
@kbailey-noaa I think we got them all (and vastly improved our docker images and deployment strategy)

**Comment by kbailey-noaa** [comment]
Looks good, thanks!
