### ISSUE TITLE
Add API links to CKAN Landing Page

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#22]

**Comment by Bobfrat** [comment]
@kknee @mwengren 
This is an old issue but looking on the landing page, it looks like the API links are available in the About Page. https://data.ioos.us/about 

Is that sufficient or is the task to get those on https://data.ioos.us?

**Comment by mwengren** [comment]
@Bobfrat this is issue is way old, before my time on Catalog even.  I'll go ahead and close it out, I think we're covered with the links on https://data.ioos.us/ and the search functionality on ioos.us.
