### ISSUE TITLE
Improve the 'Search IOOS Data' UI at top of ioos.us homepage

### ISSUE THREAD

**Issue by mwengren** [ioos/ioos-us#223]
The current 'Search IOOS Data' button on ioos.us homepage is non-intuitive.  Users must first click the button, then enter search terms into the box that appears.  

Can we replace it with a search box that is similar in size/appearance to that which appears on https://data.ioos.us/ itself (minus the tags, of course)?  The blue background isn't necessary, but a simple, prominent search box labeled 'Search IOOS Data' that spans the tiles would be a big improvement.

**Comment by mwengren** [comment]
@Bobfrat @kellydesent thanks for working on this.  I was able to run via Docker and view locally. 

Can we make the search bar a little more visually prominent?  The one on the Catalog looks like this:

![catalog_search_bar](https://user-images.githubusercontent.com/1469921/81301600-413fcf00-9047-11ea-9cb3-faa6852d1336.png)

That's a little too much, but perhaps we could use the same blue (or perhaps light gray if that doesn't look good) background/box container and put a similar sized 'Search IOOS Data' label in white to the left of the search box, and extend the search box the full width of the tile space to the right?

```
                    _______________________________________
Search IOOS Data: |    E.g. environment                  |
                    _______________________________________
```

The way it is now, I still don't think many will notice that it's there.

**Comment by kellydesent** [comment]
@Bobfrat here is the PR: https://github.com/ioos/ioos-us/pull/226
@mwengren if you think you'd like a light gray better, I can update it. Let me know. Thanks!!

**Comment by kellydesent** [comment]
![ioos-us-campure-search](https://user-images.githubusercontent.com/30243746/81980868-64e1b700-95fd-11ea-89a3-921724021e32.JPG)

**Comment by mwengren** [comment]
@kellydesent I got creative and made an alternative version for folks to review as well:

![ioos us-searchmod](https://user-images.githubusercontent.com/1469921/82072237-61a20600-96a5-11ea-9d38-8d919e0d3699.png)

Looking at them side by side, I think I like blue background better, but happy with either.  We'll see what they say.

**Comment by mwengren** [comment]
@kellydesent I asked around the office, the blue bar wins.  Please go ahead and merge/deploy these changes, thanks!

**Comment by Bobfrat** [comment]
changes have been deployed

**Comment by mwengren** [comment]
great, thanks.  closing.
