### ISSUE TITLE
Comt viewer feedback on names

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#23]
As an outsider looking at the viewer, there are a lot of unknown acronyms.  I know our viewership is still being assessed, but is there a way to spell out university or model names more or have the option to hover over the acronym and see it spelled out. ie UND - University of Notre Dame (for hover) or Univ of ND to shorten but spell out?
@kknee

**Comment by lukecampbell** [comment]
As someone who is part of IOOS, I too, often feel overwhelmed at the acronyms. Especially the ones that end in OFS.

**Comment by kknee** [comment]
@BeckyBaltes I think this will be remedied by the new homepage, good to close?

**Comment by BeckyBaltes** [comment]
Yes, I think we can close it.
