### ISSUE TITLE
Modify ioos.us homepage tiles

### ISSUE THREAD

**Issue by mwengren** [ioos/ioos-us#244]
@nguyandy Related to the SanctSound tile discussion, below is a list of changes we'd like to make to the homepage tiles on ioos.us:

* Change Data Discovery to 'IOOS Data Catalog' 2 x 1 tile w/ better graphic background graphic - screengrab of the Catalog website is ok if it looks ok (https://data.ioos.us)
* Shrink Sensor Map to 2 x 1 tile, adjust background graphic as necessary
* Shrink OSMC and OA tiles to 1 x 1
* Update Regional Associations tile to use a version of the regions map on the page it links to: https://ioos.us/regions.

I think that's all for now.  These changes can be made at any time in advance of the release of the SanctSound site/tile.

A future change will be to the IOOS Data Demo center tile pending modifications to that site first. cc @MathewBiddle on that.

**Comment by nguyandy** [comment]
Thanks @mwengren, 
@kellydesent has been handling the changes for ioos.us, I'll give her a ping for these modifications.

**Comment by kellydesent** [comment]
![july-tile-updates](https://user-images.githubusercontent.com/30243746/127172099-5f68774d-3ab4-4b01-8164-6a28638e11f0.png)

**Comment by kellydesent** [comment]
@mwengren @nguyandy, this has been updated. After all of the sizing changes, there was an extra box on a new row. So, I sized HF Radar down to one by one so they all fit on the same row. Please let me know if you'd like any changes. Here is the PR: https://github.com/ioos/ioos-us/pull/245

**Comment by nguyandy** [comment]
Thanks @kellydesent! 

@mwengren What do you think?

**Comment by mwengren** [comment]
@kellydesent Thanks for taking a crack at this!  I have a couple comments:

1. The IOOS Catalog image is not too inspiring.  Can you adapt this map image that was made using Catalog data for the background?  If it's too dark, I can try to regenerate with a lighter background map.  Will send along a lighter version as well soon.
2. For the Regional Associations map, can that be centered on the US and still look OK?  
3. Smaller HF Radar tile is ok for now I think, however we will soon have a 1x1 SanctSound tile to add and when that is included, we might want to go back to 2 x 1 HF Radar tile and perhaps expand MBON tile to 2 x 1, and maybe one more to make a full row?  Regional Associations tile might be a good candidate for 2 x 1 if necessary.

![kmjidpijidjmphck](https://user-images.githubusercontent.com/1469921/127205297-8a0ba9c7-7e74-452c-855f-876279edda72.png)

**Comment by mwengren** [comment]
@kellydesent Here's another IOOS Catalog image to use for the background tile.  Please give this one a shot instead - cropping will be necessary to only the map portion, sorry.  Thanks!

![Screenshot (43)](https://user-images.githubusercontent.com/1469921/127210714-d0bbbbaf-b5f1-4cf5-bb7f-5c71a4acc4b9.png)

**Comment by MathewBiddle** [comment]
can we update the Data Demo Center tile to be the `IOOS CodeLab`, which links to https://ioos.github.io/notebooks_demos/content/intro.html

And use the new graphic 
![test](https://github.com/ioos/ioos_code_lab/blob/master/jupyterbook/images/ioos_CodeLab_image_multi_hex.png?raw=true)

**Comment by kellydesent** [comment]
@nguyandy @mwengren @MathewBiddle Here is a screenshot of the update. Please let us know if this change as well as the previous updates are all set and we will make them live. Thanks!
<img width="1325" alt="Screen Shot 2021-09-07 at 12 30 47 PM" src="https://user-images.githubusercontent.com/30243746/132379883-b57aca2c-9248-431d-b62b-014f9a14e740.png">

**Comment by MathewBiddle** [comment]
Looks fantastic! One adjustment, could we change the text `Data Demo Center` -> `CodeLab`?

**Comment by kellydesent** [comment]
Yep, like this?
<img width="404" alt="Screen Shot 2021-09-07 at 1 04 32 PM" src="https://user-images.githubusercontent.com/30243746/132383786-54bb54e6-e864-4449-a362-5f782db88c44.png">

**Comment by MathewBiddle** [comment]
LGTM. 

Ping @mwengren for final say.

**Comment by mwengren** [comment]
Looks good to me, thanks!

**Comment by nguyandy** [comment]
@mwengren @MathewBiddle , Kelly's update has been deployed to https://ioos.us/

**Comment by mwengren** [comment]
Hi @nguyandy tile changes look good, thanks!  

Looking at the site now, I see one change we must have missed: the link for the CodeLab tile still goes to the old URL, it should be: https://ioos.github.io/ioos_code_lab/.  At the moment users have to wait for a redirect to go to the new site.

There other other changes we could make to ioos.us like updating the menu links, but for now can we get that one navigation issue resolved?

**Comment by MathewBiddle** [comment]
Good catch @mwengren! I missed that.

**Comment by kellydesent** [comment]
@mwengren @MathewBiddle I just fixed it, it should be all set now! Thanks!

**Comment by MathewBiddle** [comment]
LGTM, thanks!

**Comment by nguyandy** [comment]
I think that works!

**Comment by nguyandy** [comment]
fyi @kvmartin001

**Comment by MathewBiddle** [comment]
FYI Everything will go live on the 22nd. So, we should have pieces in place to go on next Friday.

**Comment by MathewBiddle** [comment]
Actually, can we look to push it out Thursday so other folks can take a look before Friday roll out?

**Comment by MathewBiddle** [comment]
Link should go to https://sanctsound.ioos.us/index.html (not live yet)

**Comment by nguyandy** [comment]
> Actually, can we look to push it out Thursday so other folks can take a look before Friday roll out?

Hey @MathewBiddle, so you want the updates pushed live on https://ioos.us next Thursday (21st)?

**Comment by MathewBiddle** [comment]
yeah, just so folks can test and make sure everything is working by Friday.

**Comment by nguyandy** [comment]
Sounds good! 
fyi @kvmartin001

**Comment by kvmartin001** [comment]
Hi @mwengren @MathewBiddle, I am on @nguyandy's dev team and have made the edits mentioned here.
I can't tag reviewers on the PR, so figured I would tag you here. Thanks!

**Comment by MathewBiddle** [comment]
Thanks @kvmartin001! One comment. Is it possible to have the spelled out "Sanctuary Soundscape" with "(SanctSound)" underneath it both centered if possible, both same size white text like the other tile labels?

Example: 
![image](https://user-images.githubusercontent.com/8480023/163035108-04f5bcfc-098f-4c23-ab8e-0c989e08e9c4.png)

**Comment by kvmartin001** [comment]
@MathewBiddle Sure thing, I'll change the text.

**Comment by nguyandy** [comment]
@MathewBiddle how does this look?
<img width="1029" alt="Screen Shot 2022-04-12 at 11 05 59 PM" src="https://user-images.githubusercontent.com/43226410/163092052-0e87ae6b-0119-4879-9acf-ae720df311ea.png">

**Comment by MathewBiddle** [comment]
@nguyandy Looks great! Thanks for the quick turn around. Seems like everything is in place for next Thursday.

**Comment by MathewBiddle** [comment]
FYI, the portal team will be ready for testing of connectivity NLT 1600 eastern today so that Friday April 22 AM eastern is good to go for publicity.

Let me know if there are any last minute items to address as we make the changes.

Thanks for all your hard work on this.
