### ISSUE TITLE
Search bar overlays dropdown menu on ioos.us

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-us#248]
I just noticed that when you try to look at the dropdown menus on ioos.us, the search field stays on top. I think it has something to do with scrolling the page and the search bar. See screenshots below:

![image](https://user-images.githubusercontent.com/8480023/134735858-510518d1-1afb-44e0-980c-b119f3eaa8a1.png)

![image](https://user-images.githubusercontent.com/8480023/134735627-d92b2fc1-ab99-4cbc-8119-87eef545c996.png)

**Comment by mwengren** [comment]
I noticed that as well, then it went away when I was about to file a ticket after I refreshed the issue. Seems to be an intermittent problem, should be investigated.

**Comment by benjwadams** [comment]
cc: @kellydesent

**Comment by kellydesent** [comment]
@benjwadams @nguyandy This has been fixed. Here is the PR: https://github.com/ioos/ioos-us/pull/249

**Comment by kellydesent** [comment]
@MathewBiddle @mwengren, this is live! Let me know if you still have any issues with it
<img width="1314" alt="Screen Shot 2021-09-29 at 9 53 40 AM" src="https://user-images.githubusercontent.com/30243746/135286809-0ee67fbc-c5fc-462c-a812-a944b1c864cb.png">
.

**Comment by MathewBiddle** [comment]
Awesome! Thanks for fixing that so quickly!
