### ISSUE TITLE
Begin retiring or redirecting old pages

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioos-us#25]
I'm compiling a partial list of URLs that I thought we agreed to retire.  Let's discuss whether I'm right and when it makes sense to retire/redirect.
- [ ] http://catalog.ioos.us/gliders  Retire?
- [ ] http://catalog.ioos.us/by_the_numbers/  Where will this live?
- [ ] http://catalog.ioos.us/map/ Retire?

In, general, I thought we planned to retire the entire catalog.ioos.us domain but my memory is hazy and I don't know exactly what steps to do first to determine when it's time.

**Comment by kknee** [comment]
@lukecampbell can you retire the 1st and 3rd site listed above.  The 'by-the-numbers' can stick around for now.

**Comment by lukecampbell** [comment]
What do we mean by retire?

Do we mean remove, because the front page of catalog.ioos.us still has a huge graphic that points to these?

**Comment by kknee** [comment]
the only two things we need to keep for now are 'by the numbers' and the catalog inventory.  Is it possible to keep those subfolders alive and zap catalog.ioos.us?

**Comment by dpsnowden** [comment]
Can you redirect catalog.ioos.us to www.ioos.us?

Cheers,
Derrick

Sent from my phone. Please excuse my brevity. 




On Thu, Mar 31, 2016 at 5:46 AM -0700, "Kelly Knee" <notifications@github.com> wrote:












the only two things we need to keep for now are 'by the numbers' and the catalog inventory.  Is it possible to keep those subfolders alive and zap catalog.ioos.us?

**Comment by lukecampbell** [comment]
easily. Are we ready for that? Should I shut down the service monitor or rename the site?

**Comment by kknee** [comment]
don't shut down the service monitor!  i thought renaming the site was hard?

**Comment by lukecampbell** [comment]
I can rename it from catalog.ioos.us to something like monitoring.ioos.us but I can't name it something.ioos.us/monitoring/  <-- Can't map to a subdirectory.

**Comment by dpsnowden** [comment]
I really don't remember what we decided. It was in one of the two docs we were working on. Ask Becky?

Cheers,
Derrick

Sent from my phone. Please excuse my brevity. 




On Fri, Apr 1, 2016 at 7:48 AM -0700, "Luke Campbell" <notifications@github.com> wrote:












I can rename it from catalog.ioos.us to something like monitoring.ioos.us but I can't name it something.ioos.us/monitoring/  <-- Can't map to a subdirectory.

**Comment by kknee** [comment]
we decided on: data.ioos.us/system-monitor, but maybe we need to revisit.

**Comment by lukecampbell** [comment]
I would need a few days to refactor the old catalog to do that.

**Comment by lukecampbell** [comment]
It wouldn't be pleasant.

**Comment by kknee** [comment]
@dpsnowden catalog.ioos.us now redirects to data.ioos.us and the system monitor lives on at monitor.ioos.us

http://catalog.ioos.us/gliders  -points to https://data.ioos.us/gliders/erddap/index.html, probably as a by product of redirecting catalog.ioos.us to data.ioos.us
 http://catalog.ioos.us/by_the_numbers/ - dead link now
 http://catalog.ioos.us/map/ -  dead link now

how to you want to proceed now?

**Comment by mwengren** [comment]
It looks like:

https://monitor.ioos.us/by_the_numbers/
https://monitor.ioos.us/map/ 

Are still available in the Service Monitor site.  I don't know if this is a problem or not, I don't believe we link to Service Monitor (https://monitor.ioos.us) at all from ioos.us or ioos.noaa.gov at this point.  So even if they're outdated, I don't think it's a big problem if they live on (IMO, others may disagree).

**Comment by mwengren** [comment]
Closing, monitor.ioos.us is no longer online.
