### ISSUE TITLE
Broken link on gliders.ioos.us

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/ioos-us#256]
In https://gliders.ioos.us/ under the Data Provider Tools menu there is a broken link to Compliance Checker.  Please update to https://ioos.us/compliance-checker.

**Comment by nguyandy** [comment]
@kbailey-noaa, the current Compliance Checker link seems to be working for me. (https://compliance.ioos.us/)
Do you still want to update to https://ioos.us/compliance-checker?

**Comment by kbailey-noaa** [comment]
@nguyandy The link in that Data Provider Tools menu isn't pointing to https://compliance.ioos.us/ for me, it points to gliders.ioos.us/compliance.
![image](https://user-images.githubusercontent.com/11823385/175546260-1c8baae0-852b-4d8b-a9dc-43f8333ebff0.png)

**Comment by nguyandy** [comment]
@kbailey-noaa , the url has been updated on https://gliders.ioos.us/

**Comment by kbailey-noaa** [comment]
Looks good!
