### ISSUE TITLE
Feedback form/modal window is broken

### ISSUE THREAD

**Issue by mwengren** [ioos/ioos-us#269]
If I go to https://ioos.us/ and select 'Feedback' on the left of the page, a popup window appears.

Filling in feedback in the fields is possible, however clicking submit causes the following error message to appear:

```
An Error has Occurred
```

We may want to restore this functionality.  Also seems to affect IOOS Catalog (separate or similar issue?): https://github.com/ioos/catalog/issues/89

**Comment by mwengren** [comment]
@nguyandy This issue is still present.  Can't submit feedback from the modal window.  Can you look into it?

**Comment by MathewBiddle** [comment]
data.ioos@noaa.gov and any RPS related folks...

**Comment by mwengren** [comment]
@nguyandy I did a spot check of this today and the issue still exists.   Any ideas?

**Comment by mwengren** [comment]
Works now, thanks!  Closing.
