### ISSUE TITLE
Update IOOS Logo on IOOS by the Numbers

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#27]
here: http://catalog.ioos.us/by_the_numbers/

**Comment by lukecampbell** [comment]
Yeah that's not an easy change.... That would require a fairly substantial refactor of the old catalog site. Unless you just wanna plaster the new logo over the old one without changing any of the colors or anything. 

I think a better option would be to have Ben put this graphic on this new site as a page.

**Comment by lukecampbell** [comment]
Actually, let me see if I can do something clever. I was worried that we'd have to change all of the banner code, but if I can find an IOOS logo that has a color (or make one) then I won't need to touch the banner code.

**Comment by lukecampbell** [comment]
Didn't mean to close

**Comment by kknee** [comment]
I don't think it's a bad idea to have @bnfish make a new page with that graphic, will be more consistent.

@bnfish any idea how much work?

**Comment by bnfish** [comment]
@kknee to do what? place that image on a blank page? not much work

**Comment by kknee** [comment]
yup, create a new page at metrics.ioos.us and put the 'by the numbers' image there.  if not much work let's do that.

**Comment by lukecampbell** [comment]
You guys kill me...
https://github.com/ioos/catalog/pull/443

**Comment by daf** [comment]
(Also the IOOS logo on the by the numbers graphic itself needs to updated, I think that's what @kknee was referring to by this issue)

**Comment by lukecampbell** [comment]
Well it's done now

**Comment by kknee** [comment]
@bnfish if it's easy to move the whole graphic to a page at metrics.ioos.us I'd still like to do that

**Comment by dpsnowden** [comment]
@jbosch-noaa are you seeing this convo? Can you share your draft graphic and make sure this is coordinated with your plans?

**Comment by jbosch-noaa** [comment]
Hey folks.  I'm in the process of overhauling the IOOS by the Numbers page that will live here:

IOOS.noaa.gov/about/ioos-by-the-numbers/

 when our new website launches. I am anticipating that the IOOS.us website will link back to this new page once it goes live. Here is a draft of the current graphic. 

![ioos_bythe_numbers_graphic2_v5](https://cloud.githubusercontent.com/assets/13106516/14954162/258fe6ce-103e-11e6-8151-9f59a9065c5b.png)

**Comment by kknee** [comment]
@dpsnowden this is was marked 'on hold' because we knew @jbosch-noaa had something in the works. Sounds like we can wait until the noaa.gov page and then just link there.

**Comment by lukecampbell** [comment]
I'm glad to see they kept my small contribution of the "1 IOOS" card

**Comment by jbosch-noaa** [comment]
@lukecampbell  - They = me 

Also, Zdenka and I both like it :)

**Comment by kknee** [comment]
@jbosch-noaa can we link to https://ioos.noaa.gov/about/ioos-by-the-numbers/ from the IOOS.us page now?

**Comment by jbosch-noaa** [comment]
Yes!  Please link the ioos-by-the-numbers page.

**Comment by dpsnowden** [comment]
Any word on when PR #53 will be pushed to production?  Any blockers to doing this quickly?

**Comment by kknee** [comment]
@dpsnowden pushed!
