### ISSUE TITLE
Update Map Screen Shot on gliders.ioos.us page

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#34]
and don't forget to remove the glider days ribbon first

**Comment by dpsnowden** [comment]
I've shown this page to a couple people who didn't realize that they should click on the screen shot to get to the map. Any thoughts on making it more clear?

**Comment by lukecampbell** [comment]
Have a transition when the mouse floats over the image to change it so that it looks like:

![ioos-map-overlay](https://cloud.githubusercontent.com/assets/1155163/14966582/3eaf7316-1081-11e6-819c-a6db9ee94e95.png)

?

**Comment by dpsnowden** [comment]
Seems like a good solution.

**Comment by kknee** [comment]
Agree.  @bnfish looks like you've got a little extra work to do on this.
