### ISSUE TITLE
NCEI IOOS Archive Data Portal

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/ioos-us#37]
NCEI has now made live their IOOS Archive Data Web Portal.  This is a website where people seeking to access archived IOOS data can search for and gain access to the specific data they are looking for.  

Here is the link:
http://www.nodc.noaa.gov/ioos/

To find all the RA data, people need to go to our IOOS catalog, however, if they are seeking access to data that has been archived at NCEI and is no longer available from an RA server, this website makes it easy to find.  This site as a link back to our catalog.  I think we should plan to link it from our catalog page as well (http://data.ioos.us/).

**Comment by kknee** [comment]
@jbosch-noaa how about a link from the Data menu in the ioos.us nav bar?

**Comment by jbosch-noaa** [comment]
@kknee -That sounds like a great idea!

**Comment by jbosch-noaa** [comment]
Closing this issue because the link in the data menu has been added. Thanks, @bnfish
