### ISSUE TITLE
Update EDS Tile

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#42]
@bnfish please replace the existing EDS tile image with the attached.

![thumbnail 2](https://cloud.githubusercontent.com/assets/196868/15435066/42317f88-1e88-11e6-96ff-203bdf97f50f.PNG)

**Comment by lukecampbell** [comment]
Just a design note, I crop the tiles before I add them. The whitespace around the edges makes the tiles look TERRIBLE if they're not cropped. Also, may want to consider using `background-position: center;` 

![screen shot 2016-06-16 at 1 12 55 pm](https://cloud.githubusercontent.com/assets/1155163/16125968/1c54506e-33c4-11e6-9a09-f21652d75b0c.png)
