### ISSUE TITLE
Post Manual for QC of Glider Data

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#43]
@bnfish forwarded you the doc in an email.

Please post under the documentation tab in gliders.ioos.us.  

It can be the top doc since it's the newest and it should be called, "Manual for Quality Control of Temperature and Salinity Data Observations from Gliders."  The sub text can be, "This manual describes the tests required to ensure the quality control (QC) of real-time data collected by sensors attached to profiling gliders."

**Comment by bnfish** [comment]
> forwarded you the doc in an email.

@kknee did you?

**Comment by kknee** [comment]
@bfish I think Andy took care of this one already.

Sent from my iPhone

On May 31, 2016, at 11:43 AM, Benjamin Fish <notifications@github.com<mailto:notifications@github.com>> wrote:


forwarded you the doc in an email.

@kknee<https://github.com/kknee> did you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ioos/ioos-us/issues/43#issuecomment-222729756>, or mute the thread<https://github.com/notifications/unsubscribe/AAMBBPNTto-IdvX_7pnPv7myWB2t4_OHks5qHFcMgaJpZM4Il48v>.

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.
 
Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: <http://www.rpsgroup.com>

**Comment by kknee** [comment]
@bnfish the manual is in there, but it's not at the top of the list.  Can you make that small change and then we can close this out.

**Comment by kknee** [comment]
@lukecampbell can you redeploy the site so that we can close this out?

**Comment by lukecampbell** [comment]
Is this for ioos.us or gliders.ioos.us?

**Comment by kknee** [comment]
gliders.ioos.us
