### ISSUE TITLE
Add Google Analytics Tracking Code

### ISSUE THREAD

**Issue by bnfish** [ioos/ioos-us#44]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78530076-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by RPSTJames** [comment]
Updated analytics code to be before routing.

There is no session tracking with the current code and each page view will be counted as a seperate user.

PR: #87
