### ISSUE TITLE
Add link to system documentation

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#54]
suggestion from @emiliom

@jbosch-noaa will provide more info

**Comment by jbosch-noaa** [comment]
@emiliom - If you were looking for the flow diagrams from @lukecampbell 's presentation, those are still evolving.  Once the site is fully up and running we can document how it works.  If you are looking for technical info on ioos specifications and guidelines, check this out: http://ioos.github.io/#guidelines-and-specifications:6083a88ee3411b0d17ce02d738f69d47

**Comment by kknee** [comment]
thanks @jbosch-noaa we should link to ioos.github.io site somewhere on ioos.us.

**Comment by emiliom** [comment]
Thanks, @jbosch-noaa. I think you're referring to my comment about the flow diagram in @lukecampbell's presentation. I still think it'd be useful to have it available, even in its draft from, somewhere that's not overly public such as a link somewhere from the http://ioos.github.io documentation; it could have a big "DRAFT" and disclaimer statement. And yeah, I'm very familiar with the ioos specs and guidelines docs, but thanks.

**Comment by mwengren** [comment]
@emiliom The documentation page [http://ioos.github.io/registry/ioos_registration_ngdc/](http://ioos.github.io/registry/ioos_registration_ngdc/#steps-for-registering-ioos-service-metadata:b50c3255fc3804594f54cd693ce053af) was updated to include the proposed Catalog harvesting system.  The whole document needs an update but for now the diagram is available for reference.  We're working on implementing the system itself and will be reaching out on the metadata topic.
