### ISSUE TITLE
Update sensor map tile

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/ioos-us#57]
Hi, 
The tile image for the Environmental Sensor Map looks a bit fuzzy, so attaching a new screenshot to see if this looks better:
![map_tile](https://cloud.githubusercontent.com/assets/11823385/16045572/09058090-3217-11e6-99c2-04b1f0ac99ba.PNG)
Can you please update?

**Comment by kknee** [comment]
done, closing
