### ISSUE TITLE
Consider adding a landing page for compliance checker

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#60]
It was suggested that these links:

Here's your chance to check it out and provide feedback!
http://data.ioos.us/compliance/index.html

Please submit compliance checker feedback on Github:

Bugs specific to NCEI checks or the interpretation of the NCEI specifications should be reported to 
https://github.com/ioos/cc-plugin-ncei/

All other issues should be reported here:
https://github.com/ioos/compliance-checker/

Get added to data.ioos.us/compliance, which is currently the URL for the web checker.

**Comment by kknee** [comment]
@jbosch-noaa, @mwengren  what do you think, should we move forward with a landing page for compliance checker?

**Comment by jbosch-noaa** [comment]
I say go for it.  @mwengren , what do you think?

**Comment by mwengren** [comment]
No objections here.  Looks good.

**Comment by rps-aaron** [comment]
created #182 that adds the landing page and the homepage tile.

**Comment by gitchrisadams** [comment]
@rps-aaron This is deployed at: https://ioos.us/ 
Feel free to close if this looks good.
cc: @Bobfrat

**Comment by rps-aaron** [comment]
Looks good!

**Comment by Bobfrat** [comment]
> Please submit compliance checker feedback on Github:

https://compliance.ioos.us/index.html has a feedback tab so that's probable a better place to report feedback than on Github. Plus theres a line later referencing the compliance checker github page. Maybe we should remove the above line?

> All other issues should be reported here: 
https://github.com/ioos/compliance-checker/
