### ISSUE TITLE
Add link to the technical documentation

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioos-us#61]
Not sure if this merits a tile or if it should be in the menu structure only.  This was a request from the RA Annual Meeting.

We need some work on the ioos.github.io page as well but maybe there is an interim solution.

**Comment by kknee** [comment]
@dpsnowden I think this is a duplication of #54 can we close in favor of the discussion there?

**Comment by dpsnowden** [comment]
closed in favor of #54
