### ISSUE TITLE
Add CKAN Search Box

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#66]
Allow users to kick-off a CKAN search from the IOOS.us homepage.  Doing so will bring the user to the CKAN search results page.

**Comment by lukecampbell** [comment]
Why am I assigned to this?

**Comment by bnfish** [comment]
b/c you're assigned here: https://github.com/ioos/catalog-ckan/issues/48 (?)

**Comment by kknee** [comment]
looks good @bnfish, can you update the search URL to data.ioos.us?

**Comment by kknee** [comment]
this is deployed on production
