### ISSUE TITLE
Add CKAN Featured Dataset

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#67]
Highlight the CKAN featured dataset on ioos.us homepage.

First step is for @lukecampbell to tag a CKAN data as featured.  Next step is for @bnfish to integrate on homepage

**Comment by gitchrisadams** [comment]
Due to this: https://github.com/ioos/catalog-ckan/issues/47 Can this be closed?

**Comment by mwengren** [comment]
Yes, closing.
