### ISSUE TITLE
Sensor map broken

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/ioos-us#69]
I just tried to demo http://sensors.ioos.us/ during an EarthCube Architecture planning webinar and it failed.   Some problem about https, I think.

**Comment by lukecampbell** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=sensors.ioos.us

**Comment by lukecampbell** [comment]
The certificate is using the wrong CN.

**Comment by dpsnowden** [comment]
Can this be closed?  I thought we resolved SSL issues.  @tcvance thoughts?
