### ISSUE TITLE
Update IOOS Archive Data Portal Link

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioos-us#74]
The link on the toolbar under "Data" for "IOOS Archive Data Portal" is a bad link. It's missing some punctuation. The link should take you to, https://www.nodc.noaa.gov/ioos/

**Comment by dpsnowden** [comment]
Sorry for the duplicates... #80

**Comment by kknee** [comment]
ok, closing this one then.  fix has been merged and i'll close #80 when deployed.
