### ISSUE TITLE
GLOS Data Portal Link update

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/ioos-us#75]
Hey Folks,

Got a message from Kristen Schrader at GLOS.  The link to their data portal on the [regional data portal page](https://ioos.us/regions) on ioos.us needs to be updated.  Here is a link to their new portal:  http://portal.glos.us/

**Comment by lukecampbell** [comment]
Just a heads up though, that the link in the RA drop down points to the main GLOS website, not the data portal. This is probably desirable I just want to point out the difference.

**Comment by jbosch-noaa** [comment]
Thanks @lukecampbell .  Yes, we are aware that the drop down points to the home page and the link on the map goes to the data portal. Part of me thinks that perhaps we should put a note or maybe a map title on top of the map indicating that the icons link to the data portals. @beckybaltes ?

**Comment by BeckyBaltes** [comment]
It looks like we usually use the data portal in the drop down. We should probably switch to make them consistent and I would recommend we go with data portal pages in both the drop down and on the RA Map.  If so, we need to update both GLOS and MARACOOS.
