### ISSUE TITLE
Broken link in navigation menu at the top

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioos-us#80]
The archive data portal link on this page yields an error:
https://ioos.us/

The link is currently pointing to : https://ioos.us/https//www.nodc.noaa.gov/ioos/

**Comment by kknee** [comment]
@bnfish can you update the link to: https://www.nodc.noaa.gov/ioos/

**Comment by bnfish** [comment]
@kknee it's already fixed here: https://github.com/ioos/ioos-us/pull/79

**Comment by birdage** [comment]
@kknee site is now updated, thanks to @lukecampbell
