### ISSUE TITLE
Consider making consistent which tiles use target='_blank' etc on ioos.us homepage

### ISSUE THREAD

**Issue by mwengren** [ioos/ioos-us#85]
This might improve the overall UX, IMO.  Is there a reason we can't make all of the tiles use the same browser tab/window, including the new Catalog search box?

**Comment by mwengren** [comment]
It's just a personal preference, but I'm generally not a fan of opening new tabs by default from navigation links in a website.  

I would vote for anything *.ioos.us or ioos.noaa.gov does not open a new tab, including the Catalog dataset search box, Sensor Map, etc.  These are all IOOS sites and we should allow seamless navigation as possible between the ioos.us site and these sites.  Users can always choose to open new tabs if they want to.

So I would actually say the EDS tile navigation should be copied for all the rest, and also the same behavior should happen in the nav bar at the top of the page for our own sites.  Just my personal preference like I said, others may disagree.

Anyone else want to weigh in?  @dpsnowden @kbailey-noaa @BeckyBaltes

**Comment by BeckyBaltes** [comment]
I agree with what @mwengren proposed.  I think the ioos.us or ioos.noaa.gov can all open in the same tab. I personally like new tabs because I often go back and forth between them, but I think that is the exception to the rule and most would prefer the style outlined by Micah.

**Comment by kknee** [comment]
ok.  my logic was simply that most of the sites, despite having ioos.us domains, do not have the same navigation as the core site, so uses have to press the back button to get back.

We can switch them all to not opening new tabs. Do we need to wait for anyone else to weigh in?

**Comment by Bobfrat** [comment]
@mwengren I think this ones set now. We went with your suggestion.
