### ISSUE TITLE
Add a tile for the IOOS Data Demo Center

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/ioos-us#88]
Now that the[ IOOS Data Demo Center](https://ioos.github.io/notebooks_demos/) website that @ocefpaf and I have been working on is up and running, we would like to make it more accessible to users.  A tile off the ioos.us page would be helpful.

**Comment by kknee** [comment]
@jbosch-noaa sure thing.  Any preference for for the image/icon used on the tile?

**Comment by jbosch-noaa** [comment]
@kknee - I'm working on it ...   
@bnfish- What is the optimal size and resolution of a tile picture?

**Comment by jbosch-noaa** [comment]
@bnfish - Do we need to burn in the title "Data Demo Center" or will that be something you guys put on the Tile?

Does this .png work?  Dimensions are 590 x 480 pixels at 96 ppi

![datademocenter_tile_blue](https://cloud.githubusercontent.com/assets/13106516/22563568/113c66da-e94f-11e6-8a18-9779d49762b5.png)

**Comment by bnfish** [comment]
@jbosch-noaa i'll overlay the text
in regards to its size, will this be replacing a tile? if not, where exactly should it be placed?

![image](https://cloud.githubusercontent.com/assets/385344/22565372/e252c48e-e955-11e6-8901-941bbf16b9a6.png)

**Comment by jbosch-noaa** [comment]
We shouldn't get rid of any tiles. This should be a new one.  

For symmetry we can create a tile for the HFR DAC and the ATN DAC.  I can work on graphics for both of those.  I'm also working on updating the IOOS by the Numbers graphic ... just waiting on Rob to finish his tally of the glider days.

Also, what happened to the MBON tile?  It's all white.  Looks like it's missing the picture.

**Comment by kknee** [comment]
@jbosch-noaa do you have graphics for HFR and ATN that @bnfish can get started with? If not, we could just change sizes of existing tiles to retain the grid.

**Comment by jbosch-noaa** [comment]
@kknee and @bnfish  - I am working on gathering a consensus on what image to use for those 2 DACs.  That may take a while since folks are on travel.  Perhaps adjusting the size of the images to fit the grid is the fastest way forward for now.

**Comment by kknee** [comment]
@jbosch-noaa ok, I sketched out an option for @bnfish to mockup

**Comment by bnfish** [comment]
@kknee @jbosch-noaa below is screenshot of the mockup; let me know what you think

![image](https://cloud.githubusercontent.com/assets/385344/23173866/91fceea6-f828-11e6-826d-0547e1474f3a.png)

**Comment by jbosch-noaa** [comment]
I like it.  Do you need the Data Demo Center graphic? or do you have it and just put the blue square in there as a place holder.

**Comment by bnfish** [comment]
apologies, @jbosch-noaa; graphic added:

![image](https://cloud.githubusercontent.com/assets/385344/23174225/b5dfa97a-f829-11e6-8971-e729bfac8008.png)

**Comment by jbosch-noaa** [comment]
Looks great!  Thank you, @bnfish

**Comment by jbosch-noaa** [comment]
Looping @BeckyBaltes in to this thread now that she is back :)

**Comment by lukecampbell** [comment]
It's on production
