### ISSUE TITLE
Integration of Underwatergliders.org

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#91]
gliders.ioos.us will transition to a page similar to underwatergliders.org and the current DAC content will be a subpage.

@bbaltes will further define which content on underwatergliders.org will be statis vs. dynamic and who has permissions to upload content.

**Comment by kknee** [comment]
@rps-jimfrain and @bnfish are working this.  Outline of site is here: https://docs.google.com/document/d/1-bxFbybz6olQndKYBqdHCsOxN59BjxspPxKzjTHG0wo/edit

**Comment by Bobfrat** [comment]
@BeckyBaltes can we close this issue?

**Comment by BeckyBaltes** [comment]
Yes.
