### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [ioos/ioos-us#96]
You use type `ParameterizedQuery` to an absolute 0 benefit. A simple direct query execution would have been more than sufficient, while offering all the rich formatting syntax supported by `pg-promise` ;)

**Comment by lukecampbell** [comment]
Thanks for this, just real quick, I want to make sure I have it right.

```javascript
router.get('/comt', function(req, res, next) {
  const findProjects = 'SELECT title, SUBSTRING (overview, 0, 280) as overview, title_key FROM projects ORDER BY id ASC';
  db.many(findProjects)
  .then(function (data) {

```

**Comment by vitaly-t** [comment]
That'll work ;) Just make sure to use the right database method. For example, if it can return 0 rows, you'd want to use `db.any` instead ;).

**Comment by lukecampbell** [comment]
Is the promise for `any` treated the same way as `many`? What happens if the above returns 0 results?

**Comment by vitaly-t** [comment]
See the [API](http://vitaly-t.github.io/pg-promise/Database.html).

**Comment by lukecampbell** [comment]
Thanks, I suspected it threw an error but that confirms it. Thanks for your help!
