### ISSUE TITLE
Add streaming video from Surfline

### ISSUE THREAD

**Issue by kknee** [ioos/ioos-us#98]
Becky to provide additional details

**Comment by kknee** [comment]
Here's a sample link: <iframe width="640" height="360" src="http://e.cdn-surfline.com/syndication/embed/v1/player.html?id=144653" frameborder="0" scrolling="no" allowfullscreen></iframe><div style="margin: 10px 0px;"><a href="http://www.surfline.com/surf-report/seaside-road-brigantine-mid-atlantic_144653/" target="_blank" title="Seaside Road, Brigantine Surf Report and HD Surf Cam">Seaside Road, Brigantine</a> Live HD Surf Cam. Check out more Surf Cams at <a href="http://www.surfline.com" target="_blank" title="Surfline.com - Global Surf Reports, Surf Forecasts, Live Surf Cams and Coastal Weather">Surfline.com</a></div>

**Comment by kknee** [comment]
@bnfish here's the final content for Surfline, which should be a separate page with it's own tile.  Will a frame from the video work for the tile image or do you need something higher res?

"Surfline and IOOS have joined forces to bring you a literal eye on the ocean. 

Under a cooperative research and development agreement, or CRADA, signed in 2017, Surfline began mounting live surf cameras on high-frequency radar installations within the U.S. IOOS network along the Atlantic coast.  This public-private partnership teams up existing resources on both sides to expand the utility of the radar installations and the information available to Surfline users.

The first installation to receive a camera was along the New Jersey coast with more cameras being added in the future.

The embedded video below is streaming from one of the CRADA locations.  To see more Surfline cameras, click here [http://www.surfline.com/home/index.cfm], or to learn more about IOOS' high-frequency radar work, click here [https://ioos.noaa.gov/project/hf-radar/]."

**Comment by BeckyBaltes** [comment]
@bnfish Any progress on this tile? Or an estimate for when it could be live?

**Comment by kknee** [comment]
@bnfish you can go ahead and look at this.  no need to integrate in this wordpress effort for now.

**Comment by gitchrisadams** [comment]
@Bobfrat @kknee This has been implemented by Jim. I tested and the frame loads properly. The camera looks to be down right now though, it is also not active from source at surfline as well as other sites that uses this feed. 

![image](https://user-images.githubusercontent.com/9978238/40437671-f865df28-5e83-11e8-8d6b-065471a6b69e.png)

**Comment by Bobfrat** [comment]
Available here:
https://ioos.us/surf-cam
